#!/usr/bin/env node

// The `gnutls` version is not actually stored in the `pkgver` variable, but in
// `_base_ver`

(async () => {
    const version = process.argv[2]

    const fs = require('fs')
    const lines = fs.readFileSync('PKGBUILD').toString('utf-8').split(/\r?\n/)
    lines.forEach((line, i) => {
        if ((match = line.match(/^(\s*_base_ver=)\S+/))) {
            lines[i] = `${match[1]}${version}`
        } else if ((match = line.match(/^(\s*pkgrel=)\S+/))) {
            lines[i] = `${match[1]}1`
        }
    })
    fs.writeFileSync('PKGBUILD', lines.join('\n'))
})().catch((err) => {console.log(err); process.exit(1)})
