#!/bin/sh

set -x &&
version_underscores="$(echo "$1" | tr . _)" &&
url="https://github.com/jrsoftware/issrc/releases/download/is-$version_underscores/innosetup-$1.exe" &&
curl -# -LR -D curl.log -o is.exe "$url" &&
cat curl.log &&
grep 'HTTP/.* 200' curl.log &&
./is.exe //verysilent //dir=InnoSetup //noicons //tasks= //portable=1 //lang=english \
  //SP- //SUPPRESSMSGBOXES //NORESTART //LOG=is.log &&
cat is.log &&
git add -A InnoSetup/ &&
git status