#!/usr/bin/env node

// The `openssh` version looks like this: 9.1p1. But the website calls it 9.1_P1.
// Let's auto-translate that.

(async () => {
    const version = process.argv[2].replace(/_P/, 'p')

    const fs = require('fs')
    const lines = fs.readFileSync('PKGBUILD').toString('utf-8').split(/\r?\n/)
    lines.forEach((line, i) => {
        if ((match = line.match(/^(\s*pkgver=)\S+/))) {
            lines[i] = `${match[1]}${version}`
        } else if ((match = line.match(/^(\s*pkgrel=)\S+/))) {
            lines[i] = `${match[1]}1`
        }
    })
    fs.writeFileSync('PKGBUILD', lines.join('\n'))
})().catch(console.log)
